# # # # # # # # # # # # # # # # #  #
# Windy Configuration File         #
# Change how the wind reacts here! #
# # # # # # # # # # # # # # # # #  #
Windy:
  enabled: true
  playWindNoises: true
  particles: true

  wind-push-players: true
  wind-push-mobs: true
  wind-push-entities: true

  intensity:
    low: 10
    max: 100

  # Control which Biome should be windy with the setting below
  # Simply remove the hashtag or add one before to enable/disable certain biomes
  biomes:
    - BADLANDS
    - BADLANDS_PLATEAU
    #- BAMBOO_JUNGLE
    #- BAMBOO_JUNGLE_HILLS
    - BEACH
    #- "BIRCH_FOREST"
    #- "BIRCH_FOREST_HILLS"
    #- "COLD_OCEAN"
    #- "DARK_FOREST"
    #- "DARK_FOREST_HILLS"
    - "DESERT"
    - "DESERT_HILLS"
    #- "DESERT_LAKES"
    #- "END_BARRENS"
    #- "END_HIGHLANDS"
    #- "END_MIDLANDS"
    #- "ERODED_BADLANDS"
    #- "FLOWER_FOREST"
    #- "FOREST"
    #- "FROZEN_OCEAN"
    #- "FROZEN_RIVER"
    #- "GIANT_SPRUCE_TAIGA"
    #- "GIANT_SPRUCE_TAIGA_HILLS"
    #- "GIANT_TREE_TAIGA"
    #- "GIANT_TREE_TAIGA_HILLS"
    - "GRAVELLY_MOUNTAINS"
    - "ICE_SPIKES"
    #- "JUNGLE"
    #- "JUNGLE_EDGE"
    #- "JUNGLE_HILLS"
    #- "LUKEWARM_OCEAN"
    #- "MODIFIED_BADLANDS_PLATEAU"
    #- "MODIFIED_GRAVELLY_MOUNTAINS"
    #- "MODIFIED_JUNGLE"
    #- "MODIFIED_JUNGLE_EDGE"
    #- "MODIFIED_WOODED_BADLANDS_PLATEAU"
    - "MOUNTAIN_EDGE"
    - "MOUNTAINS"
    - "MUSHROOM_FIELD_SHORE"
    #- "MUSHROOM_FIELDS"
    #- "NETHER"
    - "OCEAN"
    - "PLAINS"
    #- "RIVER"
    - "SAVANNA"
    - "SAVANNA_PLATEAU"
    - "SHATTERED_SAVANNA"
    - "SHATTERED_SAVANNA_PLATEAU"
    #- "SMALL_END_ISLANDS"
    #- "SNOWY_BEACH"
    #- "SNOWY_MOUNTAINS"
    #- "SNOWY_TAIGA"
    #- "SNOWY_TAIGA_HILLS"
    #- "SNOWY_TAIGA_MOUNTAINS"
    #- "SNOWY_TUNDRA"
    - "STONE_SHORE"
    #- "SUNFLOWER_PLAINS"
    #- "SWAMP"
    #- "SWAMP_HILLS"
    #- "TAIGA"
    #- "TAIGA_HILLS"
    #- "TAIGA_MOUNTAINS"
    #- "TALL_BIRCH_FOREST"
    #- "TALL_BIRCH_HILLS"
    #- "THE_END"
    #- "THE_VOID"
    - "WARM_OCEAN"
    #- "WOODED_BADLANDS_PLATEAU"
    #- "WOODED_HILLS"
    #- "WOODED_MOUNTAINS"